// File: src/main/kotlin/com/example/flutterassetplugin/utils/DartCodeGenerator.kt
package com.example.flutterassetplugin.utils

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.vfs.VirtualFile


object DartCodeGenerator {

    fun generate(
        assets: Map<String, List<AssetFile>>,
        naming: String,
        indicator: ProgressIndicator? = null
    ): String {
        indicator?.text = "Generating Dart code..."
        val total = assets.values.sumOf { it.size }
        var processed = 0

        val sb = StringBuilder()
        sb.append("// Auto-generated by Flutter Assets Manager\n")
        sb.append("// Do not edit manually\n\n")
        sb.append("class FlutterAssets {\n")

        for (cat in assets.keys.sorted()) {
            val className = cat.replaceFirstChar { it.uppercase() }
            sb.append("  static final $cat = _$className();\n")
        }
        sb.append("}\n\n")

        for ((cat, files) in assets) {
            val className = cat.replaceFirstChar { it.uppercase() }
            sb.append("class _$className {\n")
            val usedNames = mutableSetOf<String>()

            for (file in files.sortedBy { it.file.name }) {
                processed++
                indicator?.fraction = processed.toDouble() / total
                indicator?.text2 = "Processing: ${file.file.name}"

                var fieldName = file.file.nameWithoutExtension
                fieldName = if (naming == "camelCase") toCamelCase(fieldName) else toSnakeCase(fieldName)

                var uniqueName = fieldName
                var suffix = 1
                while (uniqueName in usedNames) {
                    uniqueName = "${fieldName}_$suffix"
                    suffix++
                }
                usedNames.add(uniqueName)

                val relativePath = file.file.path
                    .removePrefix(file.file.parent?.path ?: "")
                    .removePrefix("/")
                    .replace("\\", "/")

                sb.append("  static const String $uniqueName = '$relativePath';\n")
            }
            sb.append("}\n\n")
        }

        return sb.toString()
    }

    fun toCamelCase(name: String): String =
        name.split("-", "_", ".").mapIndexed { i, s ->
            if (i == 0) s.lowercase() else s.replaceFirstChar { it.uppercase() }
        }.joinToString("")

    fun toSnakeCase(name: String): String =
        name.replace("-", "_").replace(".", "_").lowercase()

    fun writeToFile(file: VirtualFile, content: String, indicator: ProgressIndicator? = null) {
        indicator?.text = "Writing file..."

        val bytes = content.toByteArray(Charsets.UTF_8)

        // DO NOT use runWriteAction here — must be on EDT
        // Instead: schedule on EDT from caller
        com.intellij.openapi.application.ApplicationManager.getApplication()
            .invokeLater {
                com.intellij.openapi.application.ApplicationManager.getApplication()
                    .runWriteAction {
                        file.setBinaryContent(bytes)
                    }
            }
    }
}